#!/bin/bash

if [ $# -ne 2 ]
then
        echo "usage: $(basename $0) husmow_env_dir logs_dir"
        exit 1
fi

HUSMOW_ENV_DIR=$1
LOGS_DIR=$2

cd "$HUSMOW_ENV_DIR"
bin/husmow_logger -f "$LOGS_DIR/husmow-$(date -Idate).csv"
echo husmow-$(date -Idate).csv >> $LOGS_DIR/husmow.list
